/**
 * Calendar
 */
export const CALENDAR_CREATED_PENDING = "CALENDAR_CREATED_PENDING";
export const CALENDAR_CREATED_SUCCESS = "CALENDAR_CREATED_SUCCESS";
export const CALENDAR_CREATED_ERROR = "CALENDAR_CREATED_ERROR";

export const CALENDAR_FETCHED_PENDING = "CALENDAR_FETCHED_PENDING";
export const CALENDAR_FETCHED_SUCCESS = "CALENDAR_FETCHED_SUCCESS";
export const CALENDAR_FETCHED_ERROR = "CALENDAR_FETCHED_ERROR";

/**
 * Time
 */
export const ADD_TIME = "ADD_TIME";
export const DELETE_TIME = "DELETE_TIME";

/**
 * User
 */
export const POST_USER = "POST_USER";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";