/**
 * Calendar
 */
export const CALENDAR_CREATED_PENDING = "CALENDAR_CREATED_PENDING";
export const CALENDAR_CREATED_SUCCESS = "CALENDAR_CREATED_SUCCESS";
export const CALENDAR_CREATED_ERROR = "CALENDAR_CREATED_ERROR";

export const CALENDAR_FETCHED_PENDING = "CALENDAR_FETCHED_PENDING";
export const CALENDAR_FETCHED_SUCCESS = "CALENDAR_FETCHED_SUCCESS";
export const CALENDAR_FETCHED_ERROR = "CALENDAR_FETCHED_ERROR";

/**
 * Time
 */
export const TIME_ADDED_PENDING = "TIME_ADDED_PENDING";
export const TIME_ADDED_SUCCESS = "TIME_ADDED_SUCCESS";
export const TIME_ADDED_ERROR = "TIME_ADDED_ERROR";

export const TIME_REMOVED_PENDING = "TIME_REMOVED_PENDING";
export const TIME_REMOVED_SUCCESS = "TIME_REMOVED_SUCCESS";
export const TIME_REMOVED_ERROR = "TIME_REMOVED_ERROR";

/**
 * User
 */
export const USER_CREATED_PENDING = "USER_CREATED_PENDING";
export const USER_CREATED_SUCCESS = "USER_CREATED_SUCCESS";
export const USER_CREATED_ERROR = "USER_CREATED_ERROR";